# Here we are creating pod and inside pod creating container.

kind: Pod   # creating pod
apiVersion: v1
metadata:
  name: testpod
spec:
  containers:
    - name: container1
      image: nginx
      ports:
       - containerPort: 80  # exposing port
