# Creating second pod and container.
kind: Pod
apiVersion: v1
metadata:
  name: testpod2
spec:
  containers:
    - name: container2
      image: ubuntu/apache2
      ports:
       - containerPort: 80
